
%                           PLATAFORMA BDP 2019
%
% Conjunto de abas que permite ao usuario ter acesso 
% às  informações do sistema através da interface gráfica. 

%close all
clear
clc

% Carregar todas pastas
BDP.PathSystem= pwd;
addpath(genpath(BDP.PathSystem));

% Janela principal, contém todas as abas
BDP.ID = figure(1);
BDP.DimTela = get(0,'ScreenSize');
set(BDP.ID,...
    'DockControls','off',...
    'ToolBar','none',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Name','BDP2019',...
    'Units','normalized',... 
    'Position',[0.06 0.05 0.9 0.85],...
    'Color',[0 0.4 0],...
    'Renderer','OpenGL',...
    'Resize','on',...
    'Visible','on');

%Cria as abas na janela principal
Tela.Abas = uitabgroup(BDP.ID,'Position',[0 0.05 1 0.95]);
Cam.ID = uitab(Tela.Abas, 'Title', 'Câmera','BackgroundColor',[0.9 0.9 0.9]);
Comunic.ID = uitab(Tela.Abas, 'Title', 'Comunição','BackgroundColor',[0.9 0.9 0.9]);
Calib.ID = uitab(Tela.Abas, 'Title', 'Calibração','BackgroundColor',[0.9 0.9 0.9]);
Campo.ID = uitab(Tela.Abas, 'Title', 'Campo','BackgroundColor',[0.9 0.9 0.9]);
Partida.ID = uitab(Tela.Abas, 'Title', 'Partida','BackgroundColor',[0.9 0.9 0.9]);
PWM.ID = uitab(Tela.Abas, 'Title', 'TestePMW','BackgroundColor',[0.9 0.9 0.9]);

BDP.status(1) = uicontrol(...
    'Style','text',...
    'String','',...
    'Parent',BDP.ID,...
    'Units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0 0 0.4 0.05],...
    'BackgroundColor',[0 0.2 0],...
    'ForegroundColor',[1 1 1],...
    'Visible','on','Enable','on');

BDP.status(2) = uicontrol(...
    'Style','text',...
    'String','',...
    'Parent',BDP.ID,...
    'Units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.4 0 0.6 0.05],...
    'Visible','on','Enable','on');

CamTelaMontar;
CalibTelaMontar;
CampoTelaMontar;
PartidaTelaMontar;
ComTelaMontar;
PWMTelaMontar;

CarregarCalibracao


