set(PWM.ID, ...
    'Visible','off',...
    'Position',[1 1 0.2 1].*BDP.DimTela,...
    'OuterPosition',[0.25*BDP.DimTela(3) 0.15*BDP.DimTela(4) 0.5*BDP.DimTela(3) 0.7*BDP.DimTela(4)]);

set(BDP.menu(5),'value',0)
