%Aba destinada aos testes e rotina incial dos robôs

%Inicia a comunicação
Comunic.On = uicontrol(...
    'Style','pushbutton',...
    'String','INICIAR COMUNICAÇÃO',...
    'Parent',Comunic.ID,...
    'Units','normalized',...
    'Position',[0 0.9 0.15 0.08],...
    'Visible','on','Enable','on',...
    'Callback','ComunicacaoIniciar',...
    'BackgroundColor',[0.3 0.9 0.3],...
    'ForegroundColor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',10); 


% Fecha a comunicação
Comunic.Off = uicontrol(...
    'Style','pushbutton',...
    'String','FECHAR COMUNICAÇÃO',...
    'Parent',Comunic.ID,...
    'Units','normalized',...
    'Position',[0.85 0 0.15 0.08],...
    'Visible','on','Enable','on',...
    'Callback','FecharComunicacao',...
    'BackgroundColor',[0.3 0.9 0.3],...
    'ForegroundColor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',10);

%==================================================================
%Quadro destinado a comunicação de todos os robôs ao mesmo tempo

Comunic.Painel(1) = uipanel(Comunic.ID,...
    'Title','ROTINA DOS ROBÔS',...
    'units','normalized',...
    'BackgroundColor',[0 0 0],...
    'ForegroundColor',[1 1 1],...
    'position',[0 0.3 0.2 0.4]);

Comunic.Teste(1) = uicontrol(...
    'Style','pushbutton',...
    'String','MÁXIMO PARA FRENTE',...
    'Parent',Comunic.Painel(1),...
    'Units','normalized',...
    'Position',[0 0.825 1 0.16],...
    'Visible','on','Enable','on',...
    'Callback','MaxFrente',...
    'BackgroundColor',[0.9 0.9 0.9],...
    'ForegroundColor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',10);

Comunic.Teste(2) = uicontrol(...
    'Style','pushbutton',...
    'String','MÁXIMO PARA TRÁS',...
    'Parent',Comunic.Painel(1),...
    'Units','normalized',...
    'Position',[0 0.659 1 0.16],...
    'Visible','on','Enable','on',...
    'Callback','MaxTras',...
    'BackgroundColor',[0.9 0.9 0.9],...
    'ForegroundColor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',10);

Comunic.Teste(3) = uicontrol(...
    'Style','pushbutton',...
    'String','MÁXIMO MOTOR DIREITO',...
    'Parent',Comunic.Painel(1),...
    'Units','normalized',...
    'Position',[0 0.328 1 0.16],...
    'Visible','on','Enable','on',...
    'Callback','RotMaxDireita',...
    'BackgroundColor',[0.9 0.9 0.9],...
    'ForegroundColor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',10);


Comunic.Teste(4) = uicontrol(...
    'Style','pushbutton',...
    'String','MÁXIMO MOTOR ESQUERDO',...
    'Parent',Comunic.Painel(1),...
    'Units','normalized',...
    'Position',[0 0.495 1 0.16],...
    'Visible','on','Enable','on',...
    'Callback','RotMaxEsquerdo',...
    'BackgroundColor',[0.9 0.9 0.9],...
    'ForegroundColor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',10);


Comunic.Teste(5) = uicontrol(...
    'Style','pushbutton',...
    'String','ROTAÇÃO MÁXIMA PARA A DIREITA',...
    'Parent',Comunic.Painel(1),...
    'Units','normalized',...
    'Position',[0 0.166 1 0.16],...
    'Visible','on','Enable','on',...
    'Callback','RotMaxDireita',...
    'BackgroundColor',[0.9 0.9 0.9],...
    'ForegroundColor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',10);

Comunic.Teste(6) = uicontrol(...
    'Style','pushbutton',...
    'String','ROTAÇÃO MÁXIMA PARA A ESQUERDA',...
    'Parent',Comunic.Painel(1),...
    'Units','normalized',...
    'Position',[0 0 1 0.16],...
    'Visible','on','Enable','on',...
    'Callback','RotMaxEsquerdo',...
    'BackgroundColor',[0.9 0.9 0.9],...
    'ForegroundColor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',10);

%==================================================================
%Painel destinado para enviar os valores das pontências
%desejadas para todos os robos individualmente
Comunic.Painel(2) = uipanel(Comunic.ID,...
    'Title','Envio de Pontência Individual para os Robôs',...
    'units','normalized',...
    'BackgroundColor',[0 0 0],...
    'ForegroundColor',[1 1 1],...
    'position',[0.50 0.3 0.5 0.4]);

%Botão para enviar as pontências
Comunic.Enviar(1) = uicontrol(...
    'Style','pushbutton',....
    'String','Enviar',...
    'Parent',Comunic.Painel(2),...
    'Units','normalized',...
    'Position',[0.16 0 0.67 0.19],...
    'horizontalalignment','center',...
    'fontsize',9,...
    'Callback','EnviarSeparado');


% Robô 1
Comunic.Painel(3) = uipanel(...
    'Parent',Comunic.Painel(2),...
    'Title','Rotina Robô 1',...
    'Units','normalized',...
    'position',[0 0.2 0.33 0.7]);

Comunic.Text(1) = uicontrol(...
    'Style','text',....
    'String','Potência Direita',...
    'Parent',Comunic.Painel(3),...
    'Units','normalized',...
    'Position',[0 0.76 0.5 0.2],...
    'horizontalalignment','center',...
    'fontsize',9);

Comunic.Text(2) = uicontrol(...
    'Style','text',....
    'String','Potência Esquerda',...
    'Parent',Comunic.Painel(3),...
    'Units','normalized',...
    'Position',[0.5 0.76 0.5 0.2],...
    'horizontalalignment','center',...
    'fontsize',9);

Comunic.Potencia(1) = uicontrol(...
     'Style','Edit',....
    'String','150',...
    'Parent',Comunic.Painel(3),...
    'Units','normalized',...
    'Position',[0 0 0.5 0.7],...
    'horizontalalignment','center',...
    'fontsize',9);

Comunic.Potencia(2) = uicontrol(...
     'Style','Edit',....
    'String','150',...
    'Parent',Comunic.Painel(3),...
    'Units','normalized',...
    'Position',[0.5 0 0.5 0.7],...
    'horizontalalignment','center',...
    'fontsize',9);

    
% %==================================================================
% % Robô 2
 Comunic.Painel(4) = uipanel(...
    'Parent',Comunic.Painel(2),...
    'Title','Rotina Robô 2',...
    'Units','normalized',...
    'position',[0.33 0.2 0.33 0.7]);

Comunic.Text(3) = uicontrol(...
    'Style','text',....
    'String','Potência Direita',...
    'Parent',Comunic.Painel(4),...
    'Units','normalized',...
    'Position',[0 0.76 0.5 0.2],...
    'horizontalalignment','center',...
    'fontsize',9);

Comunic.Text(4) = uicontrol(...
    'Style','text',....
    'String','Potência Esquerda',...
    'Parent',Comunic.Painel(4),...
    'Units','normalized',...
    'Position',[0.5 0.76 0.5 0.2],...
    'horizontalalignment','center',...
    'fontsize',9);

% 
Comunic.Potencia(3) = uicontrol(...
     'Style','Edit',....
    'String','150',...
    'Parent',Comunic.Painel(4),...
    'Units','normalized',...
    'Position',[0 0 0.5 0.7],...
    'horizontalalignment','center',...
    'fontsize',9);

Comunic.Potencia(4) = uicontrol(...
     'Style','Edit',....
    'String','150',...
    'Parent',Comunic.Painel(4),...
    'Units','normalized',...
    'Position',[0.5 0 0.5 0.7],...
    'horizontalalignment','center',...
    'fontsize',9);

% %==================================================================
% % Robô 3
Comunic.Painel(5) = uipanel(Comunic.Painel(2),...
    'Title','Rotina Robô 3',...
    'units','normalized',...
    'position',[0.66 0.2 0.33 0.7]);

Comunic.Text(5) = uicontrol(...
    'Style','text',....
    'String','Potência Direita',...
    'Parent',Comunic.Painel(5),...
    'Units','normalized',...
    'Position',[0 0.76 0.5 0.2],...
    'horizontalalignment','center',...
    'fontsize',9);

Comunic.Text(6) = uicontrol(...
    'Style','text',....
    'String','Potência Esquerda',...
    'Parent',Comunic.Painel(5),...
    'Units','normalized',...
    'Position',[0.5 0.76 0.5 0.2],...
    'horizontalalignment','center',...
    'fontsize',9);

% 
Comunic.Potencia(5) = uicontrol(...
    'Style','Edit',....
    'String','150',...
    'Parent',Comunic.Painel(5),...
    'Units','normalized',...
    'Position',[0 0 0.5 0.7],...
    'horizontalalignment','center',...
    'fontsize',9);

Comunic.Potencia(6) = uicontrol(...
    'Style','Edit',....
    'String','150',...
    'Parent',Comunic.Painel(5),...
    'Units','normalized',...
    'Position',[0.5 0 0.5 0.7],...
    'horizontalalignment','center',...
    'fontsize',9);

%=====================================================

%Painel destinado ao envio de Potência
%Para todos os três robôs simultâneamente

Comunic.Painel(6) = uipanel(Comunic.ID,...
    'Title','Envio de Pontência para todos os Robôs',...
    'units','normalized',...
    'BackgroundColor',[0 0 0],...
    'ForegroundColor',[1 1 1],...
    'position',[0.24 0.3 0.22 0.4]);

Comunic.Enviar(2) = uicontrol(...
    'Style','pushbutton',....
    'String','Enviar',...
    'Parent',Comunic.Painel(6),...
    'Units','normalized',...
    'Position',[0.02 0 0.96 0.19],...
    'horizontalalignment','center',...
    'fontsize',9,...
    'Callback','ComEnviar');

Comunic.Text(7) = uicontrol(...
    'Style','text',....
    'String','Potência Direita',...
    'Parent',Comunic.Painel(6),...
    'Units','normalized',...
    'Position',[0 0.7 0.5 0.2],...
    'horizontalalignment','center',...
    'fontsize',9);

Comunic.Text(8) = uicontrol(...
    'Style','text',....
    'String','Potência Esquerda',...
    'Parent',Comunic.Painel(6),...
    'Units','normalized',...
    'Position',[0.5 0.7 0.5 0.2],...
    'horizontalalignment','center',...
    'fontsize',9);

Comunic.Potencia(7) = uicontrol(...
     'Style','Edit',....
    'String','150',...
    'Parent',Comunic.Painel(6),...
    'Units','normalized',...
    'Position',[0 0.20 0.5 0.5],...
    'horizontalalignment','center',...
    'fontsize',9);

Comunic.Potencia(8) = uicontrol(...
     'Style','Edit',....
    'String','150',...
    'Parent',Comunic.Painel(6),...
    'Units','normalized',...
    'Position',[0.5 0.20 0.5 0.5],...
    'horizontalalignment','center',...
    'fontsize',9);

