Cam.ID = figure(2);

set(Cam.ID, ...
    'DockControls','off',...
    'Name','Câmera',...
    'Menubar','none',...
    'Color',[0.3 0.5 0.3],...
    'Toolbar','none',...
    'Renderer','OpenGL',...
    'NumberTitle','off',...
    'Resize','off',...
    'Visible','off',...
    'CloseRequestFcn','CamTelaFechar',...
    'Position',[0.2 1 0.2 1].*BDP.DimTela([3 2 3 4]) + [0 50 0 -80],...
    'OuterPosition',[0.2 1 0.2 1].*BDP.DimTela([3 2 3 4]) + [0 50 0 -80]);

    
Cam.menu(1) = uicontrol(...
    'Style','pushbutton',...
    'String','Conectar',...
    'Parent',Cam.ID,...
    'Units','normalized',...
    'Position',[0.1 0.9 0.8 0.08],...
    'Visible','on','Enable','on',...
    'Callback','CamConectar');

Cam.menu(2) = uicontrol(...
    'Style','pushbutton',...
    'String','Abrir Preview',...
    'Parent',Cam.ID,...
    'Units','normalized',...
    'Position',[0.1 0.8 0.8 0.08],...
    'Visible','on','Enable','off',...
    'Callback','CamAbrir');

% Cam.menu(3) = uicontrol(...
%     'Style','pushbutton',...
%     'String','Abrir Preview',...
%     'Parent',Cam.ID,...
%     'Units','normalized',...
%     'Position',[0.1 0.7 0.8 0.08],...
%     'Visible','on','Enable','off',...
%     'Callback','CamAbrir');

Cam.menu(4) = uicontrol(...
    'Style','pushbutton',...
    'String','Calibrar Cores',...
    'Parent',Cam.ID,...
    'Units','normalized',...
    'Position',[0.1 0.6 0.8 0.08],...
    'Visible','on','Enable','off',...
    'Callback','CalibTelaAbrir');

Cam.menu(5) = uicontrol(...
    'Style','pushbutton',...
    'String','Calibrar Campo',...
    'Parent',Cam.ID,...
    'Units','normalized',...
    'Position',[0.1 0.5 0.8 0.08],...
    'Visible','on','Enable','off',...
    'Callback','CampoTelaAbrir');


Cam.status(1) = uicontrol(...
    'Style','text',...
    'String','',...
    'Parent',Cam.ID,...
    'Units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.1 0.10 0.8 0.03],...
    'BackgroundColor',[0 0.2 0],...
    'ForegroundColor',[1 1 1],...
    'Visible','on','Enable','on');

Cam.status(2) = uicontrol(...
    'Style','text',...
    'String','',...
    'Parent',Cam.ID,...
    'Units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.1 0.02 0.8 0.06],...
    'Visible','on','Enable','on');

