
Filtro.ID = figure;

set(Filtro.ID, ...
    'DockControls','off',...
    'Name','Opções de filtro',...
    'Menubar','none',...
    'Toolbar','none',...
    'Renderer','OpenGL',...
    'NumberTitle','off',...
    'Resize','off',...
    'Visible','off',...
    'CloseRequestFcn','FiltroTelaFechar',...
    'Position',[0.2 1 0.2 1].*BDP.DimTela([3 2 3 4]) + [0 50 0 -80],...
    'OuterPosition',[0.2 1 0.2 1].*BDP.DimTela([3 2 3 4]) + [0 50 0 -80]);
