
    
Cam.menu(1) = uicontrol(...
    'Style','checkbox',...
    'String','CONECTAR',...
    'Parent',Cam.ID,...
    'Units','normalized',...
    'Position',[0 0.8 0.12 0.08],...
    'Visible','on','Enable','on',...
    'Callback','CamConectar',...
    'BackgroundColor',[0.3 0.9 0.3],...
    'ForegroundColor',[0 0 0],...
    'FontSize',10,...
    'FontWeight','bold'); 

Cam.menu(2) = uicontrol(...
    'Style','checkbox',...
    'String','INICIAR CAPTURA',...
    'Parent',Cam.ID,...
    'Units','normalized',...
    'Position',[0 0.7 0.12 0.08],...
    'Visible','on','Enable','off',...
    'Callback','CamCapturar',...
    'BackgroundColor',[0.3 0.9 0.3],...
    'ForegroundColor',[0 0 0],...
    'FontSize',10,...
    'FontWeight','bold'); 

Cam.menu(3) =uicontrol(...
    'Style','checkbox',...
    'String','ABRIR PREVIEW',...
    'Parent',Cam.ID,...
    'Units','normalized',...
    'Position',[0 0.6 0.12 0.08],...
    'Visible','on','Enable','off',...
    'Callback','CamAbrir',...
    'BackgroundColor',[0.3 0.9 0.3],...
    'ForegroundColor',[0 0 0],...
    'FontSize',10,...
    'FontWeight','bold'); 

